const drags = [
  /конопл/gim,
  /коноплю/gim,
  /конопля/gim,
  /коноплі/gim,
  /травку/gim,
  /травк/gim,
  /плющ/gim,

  // /Prohibited/gim,
  // /Herb/gim,
  // /Hemp/gim,
  // /Chemical/gim,
  // /flour/gim,
  // /salt/gim,
  // /Powder/gim,
  // /intoxication/gim,
  /Наркотики/gim,
  /Наркомания/gim,
  /Лекарства/gim,
  /Витаминки/gim,
  /вітамінкі/gim,
  /Порошок/gim,
  /капсула/gim,
  /ліки/gim,
  /пилюли/gim,
  /пілюлі/gim,
  /метан/gim,
  /Таблетки/gim,
  /торкнуло/gim,
  /кокаїн/gim,
  /героїн/gim,
  /марихуана/gim,
  /екстазі/gim,
  /амфетамін/gim,
  /гашиш/gim,
  /травка/gim,
  /ганджа/gim,
  /дротики/gim,
  /таблетки/gim,
  /синька/gim,
  /крек/gim,
  /сніпер/gim,
  /куріння/gim,
  /впарювання/gim,
  /шприцювання/gim,
  /нюхання/gim,
  /прокладання/gim,
  /морфін/gim,
  /кодеїн/gim,
  /амфетамін/gim,
  /метамфетамін/gim,
  /фентаніл/gim,
  /кетамін/gim,
  /метадон/gim,
  /kokayin/gim,
  // /heroyin/gim,
  // /marykhuana/gim,
  // /ekstazi/gim,
  // /amfetamin/gim,
  // /LSD/gim,
  // /hashysh/gim,
  // /travka/gim,
  // /handzha/gim,
  // /drotyky/gim,
  // /tabletky/gim,
  // /'synʹka/gim,
  // /krek/gim,
  // /sniper/gim,
  // /kurinnya/gim,
  // /vparyuvannya/gim,
  // /shprytsyuvannya/gim,
  // /nyukhannya/gim,
  // /prokladannya/gim,
  // /morfin/gim,
  // /kodeyin/gim,
  // /amfetamin/gim,
  // /metamfetamin/gim,
  // /fentanil/gim,
  // /ketamin/gim,
  // /metadon/gim,
  /кокаин/gim,
  /героин/gim,
  /марихуана/gim,
  /экстази/gim,
  /амфетамин/gim,
  /гашиш/gim,
  /травка/gim,
  /ганджа/gim,
  /дротики/gim,
  /таблетки/gim,
  /синька/gim,
  /крек/gim,
  /снипер/gim,
  /курение/gim,
  /впаривание/gim,
  /шприцевание/gim,
  /шприц/gim,
  /нюхание/gim,
  /прокладка/gim,
  /морфин/gim,
  /кодеин/gim,
  /амфетамин/gim,
  /метамфетамин/gim,
  /метадон/gim,
  // /cocaine/gim,
  // /heroin/gim,
  // /marijuana/gim,
  // /ecstasy/gim,
  // /amphetamine/gim,
  // /LSD/gim,
  // /hashish/gim,
  // /weed/gim,
  // /ganja/gim,
  // /darts/gim,
  // /pills/gim,
  // /crack/gim,
  // /sniper/gim,
  // /smoking/gim,
  // /vaping/gim,
  // /injecting/gim,
  // /sniffing/gim,
  // /laying/gim,
  // /morphine/gim,
  // /codeine/gim,
  // /amphetamine/gim,
  // /methamphetamine/gim,
  // /fentanyl/gim,
  // /ketamine/gim,
  // /methadone/gim,
];

const erotic = [
  /фалоімітатор/gim,
  /фало/gim,
  /старп/gim,

  /Еротика/gim,
  /Секс/gim,
  /еротика/gim,
  /хуй/gim,
  /пізда/gim,
  /піська/gim,
  /пісюн/gim,
  /член/gim,
  /балда/gim,
  /трахатись/gim,
  /їбатись/gim,
  /кувиркатись/gim,
  /дрочити/gim,
  /мастурбувати/gim,
  /любов/gim,
  /секс на одну ніч/gim,
  /проститутка/gim,
  /шлюха/gim,
  /шалава/gim,
  /дирка/gim,
  /вагіна/gim,
  /куннилингус/gim,
  /мінет/gim,
  // /Seks/gim,
  // /erotyka/gim,
  // /khuy/gim,
  // /xyi/gim,
  // /pizda/gim,
  // /pisʹka/gim,
  // /pisyun/gim,
  // /chlen/gim,
  // /4len/gim,
  // /balda/gim,
  // /trakhatysʹ/gim,
  // /yibatysʹ/gim,
  // /kuvyrkatysʹ/gim,
  // /drochyty/gim,
  // /masturbuvaty/gim,
  // /lyubov/gim,
  // /seks na odnu nich/gim,
  // /prostytutka/gim,
  // /shlyukha/gim,
  // /shalava/gim,
  // /dyrka/gim,
  /Секс/gim,
  /эротика/gim,
  /хуй/gim,
  /пизда/gim,
  /писька/gim,
  /писюн/gim,
  /член/gim,
  /балда/gim,
  /трахаться/gim,
  /кувыркаться/gim,
  /дрочить/gim,
  /мастурбировать/gim,
  /любовь/gim,
  /секс на одну ночь/gim,
  /проститутка/gim,
  /шлюха/gim,
  /шалава/gim,
  /дырка/gim,
  /вагина/gim,
  /куннилингус/gim,
  /мінет/gim,
  // /Seks/gim,
  // /erotika/gim,
  // /khuy/gim,
  // /xyi/gim,
  // /pizda/gim,
  // /pis'ka/gim,
  // /pisbka/gim,
  // /pisyun/gim,
  // /chlen/gim,
  // /4len/gim,
  // /balda/gim,
  // /trakhat'sya/gim,
  // /kuvyrkat'sya/gim,
  // /drochit'/gim,
  // /masturbirovat'/gim,
  // /seks na odnu noch'/gim,
  // /prostitutka/gim,
  // /shlyukha/gim,
  // /shalava/gim,
  // /dyrka/gim,
  // /Sex/gim,
  // /eroticism/gim,
  // /dick/gim,
  // /cunt/gim,
  // /pussy/gim,
  // /penis/gim,
  // /cock/gim,
  // /asshole/gim,
  // /fuck/gim,
  // /fuck/gim,
  // /tumbling/gim,
  // /jerk off/gim,
  // /masturbate/gim,
  // /love/gim,
  // /one-night stand/gim,
  // /prostitute/gim,
  // /whore/gim,
  // /slut/gim,
  // /hole/gim,
  // /cunnilingus/gim,
];

const violence = [
  /Насилля/gim,
  /насильство/gim,
  /насильника/gim,
  /насильник/gim,
  /жертвы/gim,
  /жертва/gim,
  /Зґвалтували/gim,
  /Зґвалтував/gim,
  /гвалтівник/gim,
  /Вопить/gim,
  // /scream/gim,
  // /crying/gim,
  // /Sexual/gim,
  // /raped/gim,
  // /rape/gim,
  // /Rapist/gim,
  // /Killed/gim,
  // /victims/gim,
  // /Worst/gim,
  /Вбити/gim,
  /зарізати/gim,
  /розстріляти/gim,
  /знущання/gim,
  // /Vbyty/gim,
  // /zarizaty/gim,
  // /rozstrilyaty/gim,
  // /znushchannya/gim,
  /Убить/gim,
  /зарезать/gim,
  /расстрелять/gim,
  /издевательство/gim,
  // /Ubit'/gim,
  // /zarezat'/gim,
  // /rasstrelyat'/gim,
  // /izdevatel'stvo/gim,
  // /Crime/gim,
  // /violence/gim,
];

const weapon = [
  // /Shooting/gim,
  // /revolver/gim,
  // /Gun/gim,
  // /glock/gim,
  // /Kalashnikov/gim,
  // /Fire/gim,
  /Зброя/gim,
  /війна/gim,
  /рушниця/gim,
  /пістолет/gim,
  /оружия/gim,
  /ніж/gim,
  /автомат/gim,
  /меч/gim,
  /гармата/gim,
  /стовбур/gim,
  /патрон/gim,
  /гвинтівка/gim,
  /воїн/gim,
  /танк/gim,
  /армія/gim,
  /постріл/gim,
  /бій/gim,
  /солдатів/gim,
  /кулемет/gim,
  /калашників/gim,
  /бомба/gim,
  /арбалет/gim,
  /обріз/gim,
  /вбивство/gim,
  /спис/gim,
  /куля/gim,
  /щит/gim,
  /стрільба/gim,
  /затвор/gim,
  /револьвер/gim,
  /вбивця/gim,
  /смерть/gim,
  /сокира/gim,
  /сталь/gim,
  /порох/gim,
  /міць/gim,
  /зброя/gim,
  /рана/gim,
  /полювання/gim,
  /снайпер/gim,
  /убити/gim,
  /мішень/gim,
  /вбивати/gim,
  /напад/gim,
  /мета/gim,
  /залізо/gim,
  /стріла/gim,
  /щит/gim,
  /дуло/gim,
  /удар/gim,
  /калаш/gim,
  /кілер/gim,
  /метал/gim,
  /ядерна/gim,
  /битва/gim,
  /зброяр/gim,
  /злочин/gim,
  /зло/gim,
  /вибух/gim,
  /життя/gim,
  /мафія/gim,
  /магазин/gim,
  /люди/gim,
  /бійня/gim,
  /дуель/gim,
  /базука/gim,
  /терор/gim,
  /в'язниця/gim,
  /поразка/gim,
  /ворог/gim,
  // /viyna/gim,
  // /rushnytsya/gim,
  // /pistol/gim,
  // /nizh/gim,
  // /avtomat/gim,
  // /mech/gim,
  // /harmata/gim,
  // /stovbur/gim,
  // /patron/gim,
  // /hvyntivka/gim,
  // /voyin/gim,
  // /tank/gim,
  // /armiya/gim,
  // /postril/gim,
  // /soldativ/gim,
  // /kulemet/gim,
  // /kalashnykiv/gim,
  // /bomba/gim,
  // /arbalet/gim,
  // /obriz/gim,
  // /vbyvstvo/gim,
  // /spys/gim,
  // /kulya/gim,
  // /shchyt/gim,
  // /zatvor/gim,
  // /vbyvtsya/gim,
  // /smertʹ/gim,
  // /sokyra/gim,
  // /porokh/gim,
  // /zbroya/gim,
  // /rana/gim,
  // /polyuvannya/gim,
  // /snayper/gim,
  // /ubyty/gim,
  // /mishenʹ/gim,
  // /vbyvaty/gim,
  // /napad/gim,
  // /zalizo/gim,
  // /strila/gim,
  // /shchyt/gim,
  // /dulo/gim,
  // /udar/gim,
  // /kalash/gim,
  // /kiler/gim,
  // /yaderna/gim,
  // /bytva/gim,
  // /zbroyar/gim,
  // /zlochyn/gim,
  // /zlo/gim,
  // /vybukh/gim,
  // /zhyttya/gim,
  // /mafiya/gim,
  // /mahazyn/gim,
  // /lyudy/gim,
  // /biynya/gim,
  // /bazuka/gim,
  // /teror/gim,
  // /porazka/gim,
  // /voroh/gim,
  /война/gim,
  /ружьё/gim,
  /пистолет/gim,
  /нож/gim,
  /автомат/gim,
  /меч/gim,
  /пушка/gim,
  /ствол/gim,
  /патрон/gim,
  /винтовка/gim,
  /воин/gim,
  /танк/gim,
  /армия/gim,
  /выстрел/gim,
  /бой/gim,
  /солдат/gim,
  /пулемёт/gim,
  /калашников/gim,
  /бомба/gim,
  /арбалет/gim,
  /обрез/gim,
  /убийство/gim,
  /копьё/gim,
  /пуля/gim,
  /щит/gim,
  /стрельба/gim,
  /затвор/gim,
  /револьвер/gim,
  /убийца/gim,
  /смерть/gim,
  /топор/gim,
  /сталь/gim,
  /порох/gim,
  /мощь/gim,
  /орудие/gim,
  /рана/gim,
  /охота/gim,
  /снайпер/gim,
  /убить/gim,
  /мишень/gim,
  /убивать/gim,
  /нападение/gim,
  /цель/gim,
  /железо/gim,
  /стрела/gim,
  /щит/gim,
  /дуло/gim,
  /удар/gim,
  /калаш/gim,
  /киллер/gim,
  /металл/gim,
  /ядерное/gim,
  /сражение/gim,
  /оружейник/gim,
  /преступление/gim,
  /зло/gim,
  /взрыв/gim,
  /жизнь/gim,
  /мафия/gim,
  /магазин/gim,
  /люди/gim,
  /бойня/gim,
  /дуэль/gim,
  /базука/gim,
  /террор/gim,
  /тюрьма/gim,
  /поражение/gim,
  /враг/gim,
  // /voyna/gim,
  // /pistolet/gim,
  // /nozh/gim,
  // /avtomat/gim,
  // /mech/gim,
  // /pushka/gim,
  // /stvol/gim,
  // /patron/gim,
  // /vintovka/gim,
  // /voin/gim,
  // /tank/gim,
  // /armiya/gim,
  // /vystrel/gim,
  // /soldat/gim,
  // /pulemot/gim,
  // /kalashnikov/gim,
  // /bomba/gim,
  // /arbalet/gim,
  // /obrez/gim,
  // /ubiystvo/gim,
  // /pulya/gim,
  // /shchit/gim,
  // /zatvor/gim,
  // /ubiytsa/gim,
  // /topor/gim,
  // /porokh/gim,
  // /orudiye/gim,
  // /rana/gim,
  // /okhota/gim,
  // /snayper/gim,
  // /ubit'/gim,
  // /mishen'/gim,
  // /ubivat'/gim,
  // /napadeniye/gim,
  // /zhelezo/gim,
  // /strela/gim,
  // /shchit/gim,
  // /dulo/gim,
  // /udar/gim,
  // /kalash/gim,
  // /killer/gim,
  // /yadernoye/gim,
  // /srazheniye/gim,
  // /oruzheynik/gim,
  // /prestupleniye/gim,
  // /zlo/gim,
  // /vzryv/gim,
  // /mafiya/gim,
  // /magazin/gim,
  // /lyudi/gim,
  // /boynya/gim,
  // /duel'/gim,
  // /bazuka/gim,
  // /terror/gim,
  // /porazheniye/gim,
  // /vrag/gim,
];

const alcohol = [
  /Алкоголь/gim,
  /горілка/gim,
  /вино/gim,
  /пиво/gim,
  /спирт/gim,
  /градус/gim,
  /похмілля/gim,
  /бар/gim,
  /залежність/gim,
  /пияцтво/gim,
  /бухло/gim,
  /свято/gim,
  /веселощі/gim,
  /наркотики/gim,
  /Фарма/gim,
  /шкода/gim,
  /віскі/gim,
  /сп'яніння/gim,
  /чарка/gim,
  /шампанське/gim,
  /коньяк/gim,
  /напій/gim,
  /ром/gim,
  /п'янка/gim,
  /джин/gim,
  /склянка/gim,
  /текіла/gim,
  /вечірка/gim,
  /радість/gim,
  /п'яниця/gim,
  /випивка/gim,
  /самогон/gim,
  /пляшка/gim,
  /коктейль/gim,
  /медовуха/gim,
  /абсент/gim,
  /печінка/gim,
  /звір/gim,
  /отруєння/gim,
  /джин/gim,
  /етанол/gim,
  /портвейн/gim,
  /п'яний/gim,
  /батько/gim,
  /настойка/gim,
  /бренді/gim,
  /секс/gim,
  /відхідняк/gim,
  /біла/gim,
  /гарячка/gim,
  /спиртне/gim,
  /хвороба/gim,
  /застілля/gim,
  /самбука/gim,
  /хміль/gim,
  /вискар/gim,
  /закуска/gim,
  /перегар/gim,
  /глінтвейн/gim,
  /бармен/gim,
  /блювота/gim,
  /алкаш/gim,
  /відпочинок/gim,
  // /horilka/gim,
  // /vyno/gim,
  // /pyvo/gim,
  // /spyrt/gim,
  // /hradus/gim,
  // /pokhmillya/gim,
  // /pyyatstvo/gim,
  // /bukhlo/gim,
  // /svyato/gim,
  // /veseloshchi/gim,
  // /narkotyky/gim,
  // /shkoda/gim,
  // /viski/gim,
  // /charka/gim,
  // /napiy/gim,
  // /rom/gim,
  // /dzhyn/gim,
  // /sklyanka/gim,
  // /tekila/gim,
  // /vechirka/gim,
  // /vypyvka/gim,
  // /samohon/gim,
  // /plyashka/gim,
  // /medovukha/gim,
  // /absent/gim,
  // /pechinka/gim,
  // /zvir/gim,
  // /otruyennya/gim,
  // /dzhyn/gim,
  // /etanol/gim,
  // /portveyn/gim,
  // /nastoyka/gim,
  // /brendi/gim,
  // /seks/gim,
  // /vidkhidnyak/gim,
  // /haryachka/gim,
  // /spyrtne/gim,
  // /khvoroba/gim,
  // /zastillya/gim,
  // /sambuka/gim,
  // /vyskar/gim,
  // /zakuska/gim,
  // /perehar/gim,
  // /hlintveyn/gim,
  // /barmen/gim,
  // /blyuvota/gim,
  // /alkash/gim,
  // /vidpochynok/gim,
  /водка/gim,
  /вино/gim,
  /пиво/gim,
  /спирт/gim,
  /градус/gim,
  /похмелье/gim,
  /бар/gim,
  /зависимость/gim,
  /пьянство/gim,
  /бухло/gim,
  /праздник/gim,
  /веселье/gim,
  /вред/gim,
  /виски/gim,
  /опьянение/gim,
  /рюмка/gim,
  /шампанское/gim,
  /коньяк/gim,
  /напиток/gim,
  /ром/gim,
  /пьянка/gim,
  /джин/gim,
  /стакан/gim,
  /текила/gim,
  /вечеринка/gim,
  /радость/gim,
  /пьяница/gim,
  /выпивка/gim,
  /самогон/gim,
  /бутылка/gim,
  /коктейль/gim,
  /медовуха/gim,
  /абсент/gim,
  /печень/gim,
  /злоупотребление/gim,
  /белочка/gim,
  /пьянь/gim,
  /мартини/gim,
  /зло/gim,
  /тусовка/gim,
  /трезвость/gim,
  /магазин/gim,
  /рвота/gim,
  /ликёр/gim,
  /отравление/gim,
  /джинн/gim,
  /этанол/gim,
  /портвейн/gim,
  /пьяный/gim,
  /отец/gim,
  /настойка/gim,
  /бренди/gim,
  /секс/gim,
  /отходняк/gim,
  /белая/gim,
  /горячка/gim,
  /спиртное/gim,
  /болезнь/gim,
  /застолье/gim,
  /самбука/gim,
  /хмель/gim,
  /вискарь/gim,
  /закуска/gim,
  /перегар/gim,
  /глинтвейн/gim,
  /бармен/gim,
  /блевота/gim,
  /алкаш/gim,
  /отдых/gim,
  /вода/gim,
  /корпоратив/gim,
  /хенеси/gim,
  /градусы/gim,
  /водочка/gim,
  /смелость/gim,
  /бокал/gim,
  /бодун/gim,
  // /vodka/gim,
  // /vino/gim,
  // /pivo/gim,
  // /spirt/gim,
  // /gradus/gim,
  // /zavisimost'/gim,
  // /bukhlo/gim,
  // /prazdnik/gim,
  // /narkotiki/gim,
  // /vred/gim,
  // /viski/gim,
  // /ryumka/gim,
  // /shampanskoye/gim,
  // /kon'yak/gim,
  // /napitok/gim,
  // /rom/gim,
  // /dzhin/gim,
  // /stakan/gim,
  // /tekila/gim,
  // /vecherinka/gim,
  // /vypivka/gim,
  // /samogon/gim,
  // /butylka/gim,
  // /kokteyl/gim,
  // /medovukha/gim,
  // /absent/gim,
  // /zloupotrebleniye/gim,
  // /belochka/gim,
  // /martini/gim,
  // /zlo/gim,
  // /tusovka/gim,
  // /magazin/gim,
  // /rvota/gim,
  // /likor/gim,
  // /otravleniye/gim,
  // /dzhinn/gim,
  // /etanol/gim,
  // /portveyn/gim,
  // /otets/gim,
  // /nastoyka/gim,
  // /brendi/gim,
  // /seks/gim,
  // /otkhodnyak/gim,
  // /belaya/gim,
  // /goryachka/gim,
  // /spirtnoye/gim,
  // /bolezn/gim,
  // /sambuka/gim,
  // /khmel/gim,
  // /viskar/gim,
  // /zakuska/gim,
  // /peregar/gim,
  // /glintveyn/gim,
  // /barmen/gim,
  // /blevota/gim,
  // /alkash/gim,
  // /otdykh/gim,
  // /voda/gim,
  // /korporativ/gim,
  // /khenesi/gim,
  // /gradusy/gim,
  // /vodochka/gim,
  // /bokal/gim,
  // /bodun/gim,
  // /vodka/gim,
  // /wine/gim,
  // /beer/gim,
  // /alcohol/gim,
  // /degree/gim,
  // /hangover/gim,
  // /addiction/gim,
  // /drunkenness/gim,
  // /booze/gim,
  // /drugs/gim,
  // /harm/gim,
  // /whiskey/gim,
  // /'glass/gim,
  // /champagne/gim,
  // /cognac/gim,
  // /rum/gim,
  // /booze/gim,
  // /tequila/gim,
  // /joy/gim,
  // /drunkard/gim,
  // /booze/gim,
  // /moonshine/gim,
  // /bottle/gim,
  // /cocktail/gim,
  // /mead/gim,
  // /absinthe/gim,
  // /liver/gim,
  // /abuse/gim,
  // /squirrel/gim,
  // /drunk/gim,
  // /martini/gim,
  // /evil/gim,
  // /sobriety/gim,
  // /vomiting/gim,
  // /liquor/gim,
  // /poisoning/gim,
  // /genie/gim,
  // /ethanol/gim,
  // /port/gim,
  // /wine/gim,
  // /drunk/gim,
  // /father/gim,
  // /brandy/gim,
  // /tincture/gim,
  // /sex/gim,
  // /sexy/gim,
  // /otkhodnyak/gim,
  // /delirium/gim,
  // /tremens/gim,
  // /alcohol/gim,
  // /disease/gim,
  // /feast/gim,
  // /sambuca/gim,
  // /hops/gim,
  // /whiskey/gim,
  // /appetizer/gim,
  // /fume/gim,
  // /mulled/gim,
  // /wine/gim,
  // /bartender/gim,
  // /vomit/gim,
  // /drunk/gim,
  // /corporate/gim,
  // /henesi/gim,
  // /degrees/gim,
  // /vodka/gim,
  // /courage/gim,
  // /hangover/gim,
];

const forbiddenCyrillicWords = [
  // /Medical equipment/gim,
  /экзорцист/gim,
  /опт/gim,
  /оптом/gim,
  /гурт/gim,
  /ВКонтакте/gim,
  // /Knife/gim,
  ...drags,
  ...erotic,
  ...violence,
  ...weapon,
  ...alcohol,
];

module.exports = {
  forbiddenCyrillicWords,
};
