const drags = [
  /\blcd\b/gim,
  /\btravky\b/gim,
  /\btravka\b/gim,
  /\btravk\b/gim,

  /\bProhibited\b/gim,
  /\bHerb\b/gim,
  /\bHemp\b/gim,
  /\bChemical\b/gim,
  /\bflour\b/gim,
  /\bsalt\b/gim,
  /\bPowder\b/gim,
  /\bintoxication\b/gim,
  /\btrava\b/gim,
  /\btravy\b/gim,
  /\btrave\b/gim,
  /\btravu\b/gim,
  /\btravoy\b/gim,
  /\btrave\b/gim,
  // /\bНаркотики\b/gim,
  // /\bНаркомания\b/gim,
  // /\bЛекарства\b/gim,
  // /\bВитаминки\b/gim,
  // /\bвітамінкі\b/gim,
  // /\bПорошок\b/gim,
  // /\bкапсула\b/gim,
  // /\bліки\b/gim,
  // /\bпилюли\b/gim,
  // /\bпілюлі\b/gim,
  // /\bметан\b/gim,
  // /\bТаблетки\b/gim,
  // /\bторкнуло\b/gim,
  // /\bкокаїн\b/gim,
  // /\bгероїн\b/gim,
  // /\bмарихуана\b/gim,
  // /\bекстазі\b/gim,
  // /\bамфетамін\b/gim,
  // /\bгашиш\b/gim,
  // /\bтравка\b/gim,
  // /\bганджа\b/gim,
  // /\bдротики\b/gim,
  // /\bтаблетки\b/gim,
  // /\bсинька\b/gim,
  // /\bкрек\b/gim,
  // /\bсніпер\b/gim,
  // /\bкуріння\b/gim,
  // /\bвпарювання\b/gim,
  // /\bшприцювання\b/gim,
  // /\bнюхання\b/gim,
  // /\bпрокладання\b/gim,
  // /\bморфін\b/gim,
  // /\bкодеїн\b/gim,
  // /\bамфетамін\b/gim,
  // /\bметамфетамін\b/gim,
  // /\bфентаніл\b/gim,
  // /\bкетамін\b/gim,
  // /\bметадон\b/gim,
  /\bkokayin\b/gim,
  /\bheroyin\b/gim,
  /\bmarykhuana\b/gim,
  /\bekstazi\b/gim,
  /\bamfetamin\b/gim,
  /\bLSD\b/gim,
  /\bhashysh\b/gim,
  /\btravka\b/gim,
  /\bhandzha\b/gim,
  /\bdrotyky\b/gim,
  /\btabletky\b/gim,
  /\b'synʹka\b/gim,
  /\bkrek\b/gim,
  /\bsniper\b/gim,
  /\bkurinnya\b/gim,
  /\bvparyuvannya\b/gim,
  /\bshprytsyuvannya\b/gim,
  /\bnyukhannya\b/gim,
  /\bprokladannya\b/gim,
  /\bmorfin\b/gim,
  /\bkodeyin\b/gim,
  /\bamfetamin\b/gim,
  /\bmetamfetamin\b/gim,
  /\bfentanil\b/gim,
  /\bketamin\b/gim,
  /\bmetadon\b/gim,
  // /\bкокаин\b/gim,
  // /\bгероин\b/gim,
  // /\bмарихуана\b/gim,
  // /\bэкстази\b/gim,
  // /\bамфетамин\b/gim,
  // /\bгашиш\b/gim,
  // /\bтравка\b/gim,
  // /\bганджа\b/gim,
  // /\bдротики\b/gim,
  // /\bтаблетки\b/gim,
  // /\bсинька\b/gim,
  // /\bкрек\b/gim,
  // /\bснипер\b/gim,
  // /\bкурение\b/gim,
  // /\bвпаривание\b/gim,
  // /\bшприцевание\b/gim,
  // /\bшприц\b/gim,
  // /\bнюхание\b/gim,
  // /\bпрокладка\b/gim,
  // /\bморфин\b/gim,
  // /\bкодеин\b/gim,
  // /\bамфетамин\b/gim,
  // /\bметамфетамин\b/gim,
  // /\bметадон\b/gim,
  /\bcocaine\b/gim,
  /\bheroin\b/gim,
  /\bmarijuana\b/gim,
  /\becstasy\b/gim,
  /\bamphetamine\b/gim,
  /\bLSD\b/gim,
  /\bhashish\b/gim,
  /\bweed\b/gim,
  /\bganja\b/gim,
  /\bdarts\b/gim,
  /\bpills\b/gim,
  /\bcrack\b/gim,
  /\bsniper\b/gim,
  /\bsmoking\b/gim,
  /\bvaping\b/gim,
  /\binjecting\b/gim,
  /\bsniffing\b/gim,
  /\blaying\b/gim,
  /\bmorphine\b/gim,
  /\bcodeine\b/gim,
  /\bamphetamine\b/gim,
  /\bmethamphetamine\b/gim,
  /\bfentanyl\b/gim,
  /\bketamine\b/gim,
  /\bmethadone\b/gim,
];

const erotic = [
  // /\bЕротика\b/gim,
  // /\bСекс\b/gim,
  // /\bеротика\b/gim,
  // /\bхуй\b/gim,
  // /\bпізда\b/gim,
  // /\bпіська\b/gim,
  // /\bпісюн\b/gim,
  // /\bчлен\b/gim,
  // /\bбалда\b/gim,
  // /\bтрахатись\b/gim,
  // /\bїбатись\b/gim,
  // /\bкувиркатись\b/gim,
  // /\bдрочити\b/gim,
  // /\bмастурбувати\b/gim,
  // /\bлюбов\b/gim,
  // /\bсекс на одну ніч\b/gim,
  // /\bпроститутка\b/gim,
  // /\bшлюха\b/gim,
  // /\bшалава\b/gim,
  // /\bдирка\b/gim,
  // /\bвагіна\b/gim,
  // /\bкуннилингус\b/gim,
  // /\bмінет\b/gim,
  /\bSeks\b/gim,
  /\berotyka\b/gim,
  /\bkhuy\b/gim,
  /\bxyi\b/gim,
  /\bpizda\b/gim,
  /\bpisʹka\b/gim,
  /\bpisyun\b/gim,
  /\bchlen\b/gim,
  /\b4len\b/gim,
  /\bbalda\b/gim,
  /\btrakhatysʹ\b/gim,
  /\byibatysʹ\b/gim,
  /\bkuvyrkatysʹ\b/gim,
  /\bdrochyty\b/gim,
  /\bmasturbuvaty\b/gim,
  /\blyubov\b/gim,
  /\bseks na odnu nich\b/gim,
  /\bprostytutka\b/gim,
  /\bshlyukha\b/gim,
  /\bshalava\b/gim,
  /\bdyrka\b/gim,
  // /\bСекс\b/gim,
  // /\bэротика\b/gim,
  // /\bхуй\b/gim,
  // /\bпизда\b/gim,
  // /\bписька\b/gim,
  // /\bписюн\b/gim,
  // /\bчлен\b/gim,
  // /\bбалда\b/gim,
  // /\bтрахаться\b/gim,
  // /\bкувыркаться\b/gim,
  // /\bдрочить\b/gim,
  // /\bмастурбировать\b/gim,
  // /\bлюбовь\b/gim,
  // /\bсекс на одну ночь\b/gim,
  // /\bпроститутка\b/gim,
  // /\bшлюха\b/gim,
  // /\bшалава\b/gim,
  // /\bдырка\b/gim,
  // /\bвагина\b/gim,
  // /\bкуннилингус\b/gim,
  // /\bмінет\b/gim,
  /\bSeks\b/gim,
  /\berotika\b/gim,
  /\bkhuy\b/gim,
  /\bxyi\b/gim,
  /\bpizda\b/gim,
  /\bpis'ka\b/gim,
  /\bpisbka\b/gim,
  /\bpisyun\b/gim,
  /\bchlen\b/gim,
  /\b4len\b/gim,
  /\bbalda\b/gim,
  /\btrakhat'sya\b/gim,
  /\bkuvyrkat'sya\b/gim,
  /\bdrochit'\b/gim,
  /\bmasturbirovat'\b/gim,
  /\bseks na odnu noch'\b/gim,
  /\bprostitutka\b/gim,
  /\bshlyukha\b/gim,
  /\bshalava\b/gim,
  /\bdyrka\b/gim,
  /\bSex\b/gim,
  /\beroticism\b/gim,
  /\bdick\b/gim,
  /\bcunt\b/gim,
  /\bpussy\b/gim,
  /\bpenis\b/gim,
  /\bcock\b/gim,
  /\basshole\b/gim,
  /\bfuck\b/gim,
  /\bfuck\b/gim,
  /\btumbling\b/gim,
  /\bjerk off\b/gim,
  /\bmasturbate\b/gim,
  /\blove\b/gim,
  /\bone-night stand\b/gim,
  /\bprostitute\b/gim,
  /\bwhore\b/gim,
  /\bslut\b/gim,
  /\bhole\b/gim,
  /\bcunnilingus\b/gim,
];

const violence = [
  // /\bНасилля\b/gim,
  // /\bнасильство\b/gim,
  // /\bнасильника\b/gim,
  // /\bнасильник\b/gim,
  // /\bжертвы\b/gim,
  // /\bжертва\b/gim,
  // /\bЗґвалтували\b/gim,
  // /\bЗґвалтував\b/gim,
  // /\bгвалтівник\b/gim,
  // /\bВопить\b/gim,
  /\bscream\b/gim,
  /\bcrying\b/gim,
  /\bSexual\b/gim,
  /\braped\b/gim,
  /\brape\b/gim,
  /\bRapist\b/gim,
  /\bKilled\b/gim,
  /\bvictims\b/gim,
  /\bWorst\b/gim,
  // /\bВбити\b/gim,
  // /\bзарізати\b/gim,
  // /\bрозстріляти\b/gim,
  // /\bзнущання\b/gim,
  /\bVbyty\b/gim,
  /\bzarizaty\b/gim,
  /\brozstrilyaty\b/gim,
  /\bznushchannya\b/gim,
  // /\bУбить\b/gim,
  // /\bзарезать\b/gim,
  // /\bрасстрелять\b/gim,
  // /\bиздевательство\b/gim,
  /\bUbit'\b/gim,
  /\bzarezat'\b/gim,
  /\brasstrelyat'\b/gim,
  /\bizdevatel'stvo\b/gim,
  /\bCrime\b/gim,
  /\bviolence\b/gim,
];

const weapon = [
  /\bShooting\b/gim,
  /\brevolver\b/gim,
  /\bGun\b/gim,
  /\bglock\b/gim,
  /\bKalashnikov\b/gim,
  /\bFire\b/gim,
  // /\bЗброя\b/gim,
  // /\bвійна\b/gim,
  // /\bрушниця\b/gim,
  // /\bпістолет\b/gim,
  // /\bоружия\b/gim,
  // /\bніж\b/gim,
  // /\bавтомат\b/gim,
  // /\bмеч\b/gim,
  // /\bгармата\b/gim,
  // /\bстовбур\b/gim,
  // /\bпатрон\b/gim,
  // /\bгвинтівка\b/gim,
  // /\bвоїн\b/gim,
  // /\bтанк\b/gim,
  // /\bармія\b/gim,
  // /\bпостріл\b/gim,
  // /\bбій\b/gim,
  // /\bсолдатів\b/gim,
  // /\bкулемет\b/gim,
  // /\bкалашників\b/gim,
  // /\bбомба\b/gim,
  // /\bарбалет\b/gim,
  // /\bобріз\b/gim,
  // /\bвбивство\b/gim,
  // /\bспис\b/gim,
  // /\bкуля\b/gim,
  // /\bщит\b/gim,
  // /\bстрільба\b/gim,
  // /\bзатвор\b/gim,
  // /\bревольвер\b/gim,
  // /\bвбивця\b/gim,
  // /\bсмерть\b/gim,
  // /\bсокира\b/gim,
  // /\bсталь\b/gim,
  // /\bпорох\b/gim,
  // /\bміць\b/gim,
  // /\bзброя\b/gim,
  // /\bрана\b/gim,
  // /\bполювання\b/gim,
  // /\bснайпер\b/gim,
  // /\bубити\b/gim,
  // /\bмішень\b/gim,
  // /\bвбивати\b/gim,
  // /\bнапад\b/gim,
  // /\bмета\b/gim,
  // /\bзалізо\b/gim,
  // /\bстріла\b/gim,
  // /\bщит\b/gim,
  // /\bдуло\b/gim,
  // /\bудар\b/gim,
  // /\bкалаш\b/gim,
  // /\bкілер\b/gim,
  // /\bметал\b/gim,
  // /\bядерна\b/gim,
  // /\bбитва\b/gim,
  // /\bзброяр\b/gim,
  // /\bзлочин\b/gim,
  // /\bзло\b/gim,
  // /\bвибух\b/gim,
  // /\bжиття\b/gim,
  // /\bмафія\b/gim,
  // /\bмагазин\b/gim,
  // /\bлюди\b/gim,
  // /\bбійня\b/gim,
  // /\bдуель\b/gim,
  // /\bбазука\b/gim,
  // /\bтерор\b/gim,
  // /\bв'язниця\b/gim,
  // /\bпоразка\b/gim,
  // /\bворог\b/gim,
  /\bviyna\b/gim,
  /\brushnytsya\b/gim,
  /\bpistol\b/gim,
  /\bnizh\b/gim,
  /\bavtomat\b/gim,
  /\bmech\b/gim,
  /\bharmata\b/gim,
  /\bstovbur\b/gim,
  /\bpatron\b/gim,
  /\bhvyntivka\b/gim,
  /\bvoyin\b/gim,
  /\btank\b/gim,
  /\barmiya\b/gim,
  /\bpostril\b/gim,
  /\bsoldativ\b/gim,
  /\bkulemet\b/gim,
  /\bkalashnykiv\b/gim,
  /\bbomba\b/gim,
  /\barbalet\b/gim,
  /\bobriz\b/gim,
  /\bvbyvstvo\b/gim,
  /\bspys\b/gim,
  /\bkulya\b/gim,
  /\bshchyt\b/gim,
  /\bzatvor\b/gim,
  /\bvbyvtsya\b/gim,
  /\bsmertʹ\b/gim,
  /\bsokyra\b/gim,
  /\bporokh\b/gim,
  /\bzbroya\b/gim,
  /\brana\b/gim,
  /\bpolyuvannya\b/gim,
  /\bsnayper\b/gim,
  /\bubyty\b/gim,
  /\bmishenʹ\b/gim,
  /\bvbyvaty\b/gim,
  /\bnapad\b/gim,
  /\bzalizo\b/gim,
  /\bstrila\b/gim,
  /\bshchyt\b/gim,
  /\bdulo\b/gim,
  /\budar\b/gim,
  /\bkalash\b/gim,
  /\bkiler\b/gim,
  /\byaderna\b/gim,
  /\bbytva\b/gim,
  /\bzbroyar\b/gim,
  /\bzlochyn\b/gim,
  /\bzlo\b/gim,
  /\bvybukh\b/gim,
  /\bzhyttya\b/gim,
  /\bmafiya\b/gim,
  /\bmahazyn\b/gim,
  /\blyudy\b/gim,
  /\bbiynya\b/gim,
  /\bbazuka\b/gim,
  /\bteror\b/gim,
  /\bporazka\b/gim,
  /\bvoroh\b/gim,
  // /\bвойна\b/gim,
  // /\bружьё\b/gim,
  // /\bпистолет\b/gim,
  // /\bнож\b/gim,
  // /\bавтомат\b/gim,
  // /\bмеч\b/gim,
  // /\bпушка\b/gim,
  // /\bствол\b/gim,
  // /\bпатрон\b/gim,
  // /\bвинтовка\b/gim,
  // /\bвоин\b/gim,
  // /\bтанк\b/gim,
  // /\bармия\b/gim,
  // /\bвыстрел\b/gim,
  // /\bбой\b/gim,
  // /\bсолдат\b/gim,
  // /\bпулемёт\b/gim,
  // /\bкалашников\b/gim,
  // /\bбомба\b/gim,
  // /\bарбалет\b/gim,
  // /\bобрез\b/gim,
  // /\bубийство\b/gim,
  // /\bкопьё\b/gim,
  // /\bпуля\b/gim,
  // /\bщит\b/gim,
  // /\bстрельба\b/gim,
  // /\bзатвор\b/gim,
  // /\bревольвер\b/gim,
  // /\bубийца\b/gim,
  // /\bсмерть\b/gim,
  // /\bтопор\b/gim,
  // /\bсталь\b/gim,
  // /\bпорох\b/gim,
  // /\bмощь\b/gim,
  // /\bорудие\b/gim,
  // /\bрана\b/gim,
  // /\bохота\b/gim,
  // /\bснайпер\b/gim,
  // /\bубить\b/gim,
  // /\bмишень\b/gim,
  // /\bубивать\b/gim,
  // /\bнападение\b/gim,
  // /\bцель\b/gim,
  // /\bжелезо\b/gim,
  // /\bстрела\b/gim,
  // /\bщит\b/gim,
  // /\bдуло\b/gim,
  // /\bудар\b/gim,
  // /\bкалаш\b/gim,
  // /\bкиллер\b/gim,
  // /\bметалл\b/gim,
  // /\bядерное\b/gim,
  // /\bсражение\b/gim,
  // /\bоружейник\b/gim,
  // /\bпреступление\b/gim,
  // /\bзло\b/gim,
  // /\bвзрыв\b/gim,
  // /\bжизнь\b/gim,
  // /\bмафия\b/gim,
  // /\bмагазин\b/gim,
  // /\bлюди\b/gim,
  // /\bбойня\b/gim,
  // /\bдуэль\b/gim,
  // /\bбазука\b/gim,
  // /\bтеррор\b/gim,
  // /\bтюрьма\b/gim,
  // /\bпоражение\b/gim,
  // /\bвраг\b/gim,
  /\bvoyna\b/gim,
  /\bpistolet\b/gim,
  /\bnozh\b/gim,
  /\bavtomat\b/gim,
  /\bmech\b/gim,
  /\bpushka\b/gim,
  /\bstvol\b/gim,
  /\bpatron\b/gim,
  /\bvintovka\b/gim,
  /\bvoin\b/gim,
  /\btank\b/gim,
  /\barmiya\b/gim,
  /\bvystrel\b/gim,
  /\bsoldat\b/gim,
  /\bpulemot\b/gim,
  /\bkalashnikov\b/gim,
  /\bbomba\b/gim,
  /\barbalet\b/gim,
  /\bobrez\b/gim,
  /\bubiystvo\b/gim,
  /\bpulya\b/gim,
  /\bshchit\b/gim,
  /\bzatvor\b/gim,
  /\bubiytsa\b/gim,
  /\btopor\b/gim,
  /\bporokh\b/gim,
  /\borudiye\b/gim,
  /\brana\b/gim,
  /\bokhota\b/gim,
  /\bsnayper\b/gim,
  /\bubit'\b/gim,
  /\bmishen'\b/gim,
  /\bubivat'\b/gim,
  /\bnapadeniye\b/gim,
  /\bzhelezo\b/gim,
  /\bstrela\b/gim,
  /\bshchit\b/gim,
  /\bdulo\b/gim,
  /\budar\b/gim,
  /\bkalash\b/gim,
  /\bkiller\b/gim,
  /\byadernoye\b/gim,
  /\bsrazheniye\b/gim,
  /\boruzheynik\b/gim,
  /\bprestupleniye\b/gim,
  /\bzlo\b/gim,
  /\bvzryv\b/gim,
  /\bmafiya\b/gim,
  /\bmagazin\b/gim,
  /\blyudi\b/gim,
  /\bboynya\b/gim,
  /\bduel'\b/gim,
  /\bbazuka\b/gim,
  /\bterror\b/gim,
  /\bporazheniye\b/gim,
  /\bvrag\b/gim,
];

const alcohol = [
  // /\bАлкоголь\b/gim,
  // /\bгорілка\b/gim,
  // /\bвино\b/gim,
  // /\bпиво\b/gim,
  // /\bспирт\b/gim,
  // /\bградус\b/gim,
  // /\bпохмілля\b/gim,
  // /\bбар\b/gim,
  // /\bзалежність\b/gim,
  // /\bпияцтво\b/gim,
  // /\bбухло\b/gim,
  // /\bсвято\b/gim,
  // /\bвеселощі\b/gim,
  // /\bнаркотики\b/gim,
  // /\bФарма\b/gim,
  // /\bшкода\b/gim,
  // /\bвіскі\b/gim,
  // /\bсп'яніння\b/gim,
  // /\bчарка\b/gim,
  // /\bшампанське\b/gim,
  // /\bконьяк\b/gim,
  // /\bнапій\b/gim,
  // /\bром\b/gim,
  // /\bп'янка\b/gim,
  // /\bджин\b/gim,
  // /\bсклянка\b/gim,
  // /\bтекіла\b/gim,
  // /\bвечірка\b/gim,
  // /\bрадість\b/gim,
  // /\bп'яниця\b/gim,
  // /\bвипивка\b/gim,
  // /\bсамогон\b/gim,
  // /\bпляшка\b/gim,
  // /\bкоктейль\b/gim,
  // /\bмедовуха\b/gim,
  // /\bабсент\b/gim,
  // /\bпечінка\b/gim,
  // /\bзвір\b/gim,
  // /\bотруєння\b/gim,
  // /\bджин\b/gim,
  // /\bетанол\b/gim,
  // /\bпортвейн\b/gim,
  // /\bп'яний\b/gim,
  // /\bбатько\b/gim,
  // /\bнастойка\b/gim,
  // /\bбренді\b/gim,
  // /\bсекс\b/gim,
  // /\bвідхідняк\b/gim,
  // /\bбіла\b/gim,
  // /\bгарячка\b/gim,
  // /\bспиртне\b/gim,
  // /\bхвороба\b/gim,
  // /\bзастілля\b/gim,
  // /\bсамбука\b/gim,
  // /\bхміль\b/gim,
  // /\bвискар\b/gim,
  // /\bзакуска\b/gim,
  // /\bперегар\b/gim,
  // /\bглінтвейн\b/gim,
  // /\bбармен\b/gim,
  // /\bблювота\b/gim,
  // /\bалкаш\b/gim,
  // /\bвідпочинок\b/gim,
  /\bhorilka\b/gim,
  /\bvyno\b/gim,
  /\bpyvo\b/gim,
  /\bspyrt\b/gim,
  /\bhradus\b/gim,
  /\bpokhmillya\b/gim,
  /\bpyyatstvo\b/gim,
  /\bbukhlo\b/gim,
  /\bsvyato\b/gim,
  /\bveseloshchi\b/gim,
  /\bnarkotyky\b/gim,
  /\bshkoda\b/gim,
  /\bviski\b/gim,
  /\bcharka\b/gim,
  /\bnapiy\b/gim,
  /\brom\b/gim,
  /\bdzhyn\b/gim,
  /\bsklyanka\b/gim,
  /\btekila\b/gim,
  /\bvechirka\b/gim,
  /\bvypyvka\b/gim,
  /\bsamohon\b/gim,
  /\bplyashka\b/gim,
  /\bmedovukha\b/gim,
  /\babsent\b/gim,
  /\bpechinka\b/gim,
  /\bzvir\b/gim,
  /\botruyennya\b/gim,
  /\bdzhyn\b/gim,
  /\betanol\b/gim,
  /\bportveyn\b/gim,
  /\bnastoyka\b/gim,
  /\bbrendi\b/gim,
  /\bseks\b/gim,
  /\bvidkhidnyak\b/gim,
  /\bharyachka\b/gim,
  /\bspyrtne\b/gim,
  /\bkhvoroba\b/gim,
  /\bzastillya\b/gim,
  /\bsambuka\b/gim,
  /\bvyskar\b/gim,
  /\bzakuska\b/gim,
  /\bperehar\b/gim,
  /\bhlintveyn\b/gim,
  /\bbarmen\b/gim,
  /\bblyuvota\b/gim,
  /\balkash\b/gim,
  /\bvidpochynok\b/gim,
  // /\bводка\b/gim,
  // /\bвино\b/gim,
  // /\bпиво\b/gim,
  // /\bспирт\b/gim,
  // /\bградус\b/gim,
  // /\bпохмелье\b/gim,
  // /\bбар\b/gim,
  // /\bзависимость\b/gim,
  // /\bпьянство\b/gim,
  // /\bбухло\b/gim,
  // /\bпраздник\b/gim,
  // /\bвеселье\b/gim,
  // /\bвред\b/gim,
  // /\bвиски\b/gim,
  // /\bопьянение\b/gim,
  // /\bрюмка\b/gim,
  // /\bшампанское\b/gim,
  // /\bконьяк\b/gim,
  // /\bнапиток\b/gim,
  // /\bром\b/gim,
  // /\bпьянка\b/gim,
  // /\bджин\b/gim,
  // /\bстакан\b/gim,
  // /\bтекила\b/gim,
  // /\bвечеринка\b/gim,
  // /\bрадость\b/gim,
  // /\bпьяница\b/gim,
  // /\bвыпивка\b/gim,
  // /\bсамогон\b/gim,
  // /\bбутылка\b/gim,
  // /\bкоктейль\b/gim,
  // /\bмедовуха\b/gim,
  // /\bабсент\b/gim,
  // /\bпечень\b/gim,
  // /\bзлоупотребление\b/gim,
  // /\bбелочка\b/gim,
  // /\bпьянь\b/gim,
  // /\bмартини\b/gim,
  // /\bзло\b/gim,
  // /\bтусовка\b/gim,
  // /\bтрезвость\b/gim,
  // /\bмагазин\b/gim,
  // /\bрвота\b/gim,
  // /\bликёр\b/gim,
  // /\bотравление\b/gim,
  // /\bджинн\b/gim,
  // /\bэтанол\b/gim,
  // /\bпортвейн\b/gim,
  // /\bпьяный\b/gim,
  // /\bотец\b/gim,
  // /\bнастойка\b/gim,
  // /\bбренди\b/gim,
  // /\bсекс\b/gim,
  // /\bотходняк\b/gim,
  // /\bбелая\b/gim,
  // /\bгорячка\b/gim,
  // /\bспиртное\b/gim,
  // /\bболезнь\b/gim,
  // /\bзастолье\b/gim,
  // /\bсамбука\b/gim,
  // /\bхмель\b/gim,
  // /\bвискарь\b/gim,
  // /\bзакуска\b/gim,
  // /\bперегар\b/gim,
  // /\bглинтвейн\b/gim,
  // /\bбармен\b/gim,
  // /\bблевота\b/gim,
  // /\bалкаш\b/gim,
  // /\bотдых\b/gim,
  // /\bвода\b/gim,
  // /\bкорпоратив\b/gim,
  // /\bхенеси\b/gim,
  // /\bградусы\b/gim,
  // /\bводочка\b/gim,
  // /\bсмелость\b/gim,
  // /\bбокал\b/gim,
  // /\bбодун\b/gim,
  /\bvodka\b/gim,
  /\bvino\b/gim,
  /\bpivo\b/gim,
  /\bspirt\b/gim,
  /\bgradus\b/gim,
  /\bzavisimost'\b/gim,
  /\bbukhlo\b/gim,
  /\bprazdnik\b/gim,
  /\bnarkotiki\b/gim,
  /\bvred\b/gim,
  /\bviski\b/gim,
  /\bryumka\b/gim,
  /\bshampanskoye\b/gim,
  /\bkon'yak\b/gim,
  /\bnapitok\b/gim,
  /\brom\b/gim,
  /\bdzhin\b/gim,
  /\bstakan\b/gim,
  /\btekila\b/gim,
  /\bvecherinka\b/gim,
  /\bvypivka\b/gim,
  /\bsamogon\b/gim,
  /\bbutylka\b/gim,
  /\bkokteyl\b/gim,
  /\bmedovukha\b/gim,
  /\babsent\b/gim,
  /\bzloupotrebleniye\b/gim,
  /\bbelochka\b/gim,
  /\bmartini\b/gim,
  /\bzlo\b/gim,
  /\btusovka\b/gim,
  /\bmagazin\b/gim,
  /\brvota\b/gim,
  /\blikor\b/gim,
  /\botravleniye\b/gim,
  /\bdzhinn\b/gim,
  /\betanol\b/gim,
  /\bportveyn\b/gim,
  /\botets\b/gim,
  /\bnastoyka\b/gim,
  /\bbrendi\b/gim,
  /\bseks\b/gim,
  /\botkhodnyak\b/gim,
  /\bbelaya\b/gim,
  /\bgoryachka\b/gim,
  /\bspirtnoye\b/gim,
  /\bbolezn\b/gim,
  /\bsambuka\b/gim,
  /\bkhmel\b/gim,
  /\bviskar\b/gim,
  /\bzakuska\b/gim,
  /\bperegar\b/gim,
  /\bglintveyn\b/gim,
  /\bbarmen\b/gim,
  /\bblevota\b/gim,
  /\balkash\b/gim,
  /\botdykh\b/gim,
  /\bvoda\b/gim,
  /\bkorporativ\b/gim,
  /\bkhenesi\b/gim,
  /\bgradusy\b/gim,
  /\bvodochka\b/gim,
  /\bbokal\b/gim,
  /\bbodun\b/gim,
  /\bvodka\b/gim,
  /\bwine\b/gim,
  /\bbeer\b/gim,
  /\balcohol\b/gim,
  /\bdegree\b/gim,
  /\bhangover\b/gim,
  /\baddiction\b/gim,
  /\bdrunkenness\b/gim,
  /\bbooze\b/gim,
  /\bdrugs\b/gim,
  /\bharm\b/gim,
  /\bwhiskey\b/gim,
  /\b'glass\b/gim,
  /\bchampagne\b/gim,
  /\bcognac\b/gim,
  /\brum\b/gim,
  /\bbooze\b/gim,
  /\btequila\b/gim,
  /\bjoy\b/gim,
  /\bdrunkard\b/gim,
  /\bbooze\b/gim,
  /\bmoonshine\b/gim,
  /\bbottle\b/gim,
  /\bcocktail\b/gim,
  /\bmead\b/gim,
  /\babsinthe\b/gim,
  /\bliver\b/gim,
  /\babuse\b/gim,
  /\bsquirrel\b/gim,
  /\bdrunk\b/gim,
  /\bmartini\b/gim,
  /\bevil\b/gim,
  /\bsobriety\b/gim,
  /\bvomiting\b/gim,
  /\bliquor\b/gim,
  /\bpoisoning\b/gim,
  /\bgenie\b/gim,
  /\bethanol\b/gim,
  /\bport\b/gim,
  /\bwine\b/gim,
  /\bdrunk\b/gim,
  /\bfather\b/gim,
  /\bbrandy\b/gim,
  /\btincture\b/gim,
  /\bsex\b/gim,
  /\bsexy\b/gim,
  /\botkhodnyak\b/gim,
  /\bdelirium\b/gim,
  /\btremens\b/gim,
  /\balcohol\b/gim,
  /\bdisease\b/gim,
  /\bfeast\b/gim,
  /\bsambuca\b/gim,
  /\bhops\b/gim,
  /\bwhiskey\b/gim,
  /\bappetizer\b/gim,
  /\bfume\b/gim,
  /\bmulled\b/gim,
  /\bwine\b/gim,
  /\bbartender\b/gim,
  /\bvomit\b/gim,
  /\bdrunk\b/gim,
  /\bcorporate\b/gim,
  /\bhenesi\b/gim,
  /\bdegrees\b/gim,
  /\bvodka\b/gim,
  /\bcourage\b/gim,
  /\bhangover\b/gim,
];

const safeDesc = [
  // POSSIBLE,
  /\bLIKELY\b/gim,
  /\bVERY_LIKELY\b/gim,
];

const forbiddenEngWords = [
  /\bMedical equipment\b/gim,
  // /\bэкзорцист\b/gim,
  // /\bопт\b/gim,
  // /\bоптом\b/gim,
  // /\bгурт\b/gim,
  // /\bВКонтакте\b/gim,
  /\bKnife\b/gim,
  ...drags,
  ...erotic,
  ...violence,
  ...weapon,
  ...alcohol,
  ...safeDesc,
];

module.exports = {
  forbiddenEngWords,
  safeDesc,
};
